parserOptions:
  ecmaVersion: 6

env:
  browser: true
  webextensions: true
  es6: true

globals:
  _: false
  requirejs: false
  require: false
  define: false

extends: eslint:recommended
rules:
  comma-dangle: [ warn, always-multiline]
  eqeqeq: [ error, smart ]

root: true
