parserOptions:
  ecmaVersion: 6

env:
  browser: true
  webextensions: true
  es6: true

extends: eslint:recommended
rules:
  comma-dangle: [ warn, always-multiline]
  eqeqeq: [ error, smart ]
  no-console: off

root: true
